# Generated by Django 5.2.4 on 2025-07-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_year_of_publication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title']},
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['author', 'year_of_publication'], name='books_book_author__b47e02_idx'),
        ),
    ]
